// Source is auto-generated by miru. DO NOT EDIT

package todo

import (
	"github.com/influx6/groundlayer/pkg/domu"

	helpers "github.com/influx6/groundlayer/pkg/helpers"
	peji "github.com/influx6/groundlayer/pkg/peji"
)

// Generated go-based types from template

// Generated go-based functions from template

// definedTemplate2 is a template defined in "blocks.html#header"
func definedTemplate2(page *peji.Page, ctx string, rootDoc *domu.Node) {
	var text4 = domu.Text("\n\t")
	text4.Mount(rootDoc)
	var node5 = domu.Element("h1").UseID("node5")
	var text6 = domu.Text("")
	text6.Mount(node5)
	helpers.AttachToNode(ctx, node5)

	var text7 = domu.Text("")
	text7.Mount(node5)

	node5.Mount(rootDoc)

	var text8 = domu.Text("\n")
	text8.Mount(rootDoc)

}

// Generated go-based rendering of output template

func RenderLayout(page *peji.Page, ctx peji.Data, rootDoc *domu.Node) {
	var text1 = domu.Text("\n\n\n")
	text1.Mount(rootDoc)

	definedTemplate2(page, ctx.Path, rootDoc)
}
