// Source is auto-generated by miru. DO NOT EDIT

package todo

import (
	"github.com/influx6/groundlayer/pkg/domu"

	helpers "github.com/influx6/groundlayer/pkg/helpers"
	peji "github.com/influx6/groundlayer/pkg/peji"
)

// Generated go-based types from template

type ItemList []string

type Product struct {
	Items ItemList
}

// Generated go-based functions from template

// definedTemplate2 is a template defined in "drop.render.html"
func definedTemplate2(page *peji.Page, ctx peji.Data, rootDoc *domu.Node) {
	var text4 = domu.Text("\n\n\n")
	text4.Mount(rootDoc)
	var text5 = domu.Text("\n\n")
	text5.Mount(rootDoc)
	var text6 = domu.Text("\n")
	text6.Mount(rootDoc)
	var text7 = domu.Text("\n\n")
	text7.Mount(rootDoc)
	var node8 = domu.Element("h2").UseID("node8")
	var text9 = domu.Text("")
	text9.Mount(node8)
	helpers.AttachToNode(ctx, node8)

	var text10 = domu.Text("")
	text10.Mount(node8)

	node8.Mount(rootDoc)

}

// definedTemplate5 is a template defined in "blocks.html"
func definedTemplate5(page *peji.Page, ctx string, rootDoc *domu.Node) {
	var text7 = domu.Text("\n\n")
	text7.Mount(rootDoc)
	var text8 = domu.Text("\n\n")
	text8.Mount(rootDoc)
	var node9 = domu.Element("h1").UseID("node9")
	var text10 = domu.Text("")
	text10.Mount(node9)
	helpers.AttachToNode(ctx, node9)

	var text11 = domu.Text("")
	text11.Mount(node9)

	node9.Mount(rootDoc)

	var text12 = domu.Text("\n")
	text12.Mount(rootDoc)
	var node13 = domu.Element("p").UseID("node13")
	var text14 = domu.Text("Celery")
	text14.Mount(node13)

	node13.Mount(rootDoc)

}

// Generated go-based rendering of output template

func RenderLayout(page *peji.Page, ctx peji.Data, rootDoc *domu.Node) {
	var text1 = domu.Text("\n\n")
	text1.Mount(rootDoc)

	definedTemplate2(page, ctx, rootDoc)
	var text4 = domu.Text("\n\n")
	text4.Mount(rootDoc)

	definedTemplate5(page, ctx.Path, rootDoc)

}
